# Generated by Django 4.1.10 on 2023-08-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
