from django.urls import path

from . import views

urlpatterns = [
    path('create_animal/', views.create_animal, name='create_animal'),
    path('create_labor/', views.create_labor, name='create_labor'),
    path('create_milk_expense/', views.create_expense, name='create_milk_expense'),
    path('create_grass/', views.create_grass, name='create_grass'),
    path('edit_animal/<int:id>/', views.update_animal, name='edit_animal'),
    path('edit_labor/<int:id>/', views.update_labor, name='edit_labor'),
    path('edit_milk_expense/<int:id>/', views.update_expense, name='edit_expense'),
    path('edit_grass/<int:id>/', views.update_grass, name='edit_grass'),
    path('delete_animal/<int:id>/', views.delete_animal, name='delete_animal'),
    path('delete_labor/<int:id>/', views.delete_labor, name='delete_labor'),
    path('delete_milk_expense/<int:id>/', views.delete_expense, name='delete_expense'),
    path('delete_grass/<int:id>/', views.delete_grass, name='delete_grass'),
    path('create_payment/', views.create_payment, name='create_payment'),
    path('create_daily_production/', views.create_daily_production, name='create_daily_production'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('edit_payment/<int:id>/', views.update_payment, name='edit_payment'),
    path('edit_daily_production/<int:id>/', views.update_daily_production,
            name='edit_daily_production'),
    path('edit_customer/<int:id>/', views.update_customer, name='edit_customer'),
    path('delete_payment/<int:id>/', views.delete_payment, name='delete_payment'),
    path('delete_daily_production/<int:id>/', views.delete_daily_production,
            name='delete_daily_production'),
    path('delete_customer/<int:id>/', views.delete_customer, name='delete_customer'),
    path('create_daily_delivery/', views.create_daily_delivery, name='create_daily_delivery'),
    path('edit_daily_delivery/<int:id>/', views.update_daily_delivery,
            name='edit_daily_delivery'),
    path('delete_daily_delivery/<int:id>/', views.delete_daily_delivery,
            name='delete_daily_delivery'),
    path('display_animals/', views.view_animal, name='display_animals'),
    path('display_labor/', views.view_labor, name='display_labor'),
    path('display_milk_expenses/', views.view_expense, name='display_milk_expenses'),
    path('display_grass/', views.view_grass, name='display_grass'),
    path('display_payments/', views.view_payment, name='display_payments'),
    path('display_daily_production/', views.view_daily_production, name='display_daily_production'),
    path('display_customers/', views.view_customer, name='display_customers'),
    path('display_daily_delivery/', views.view_daily_delivery, name='display_daily_delivery'),
]
