# Generated by Django 4.1.10 on 2023-08-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_paid', models.BooleanField(default=False)),
                ('tenant_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.house')),
            ],
        ),
    ]
