# Generated by Django 4.1.10 on 2023-08-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_pending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.house')),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('gpay', 'GPay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm')], max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rental_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rentalperson')),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
