# Generated by Django 4.1.10 on 2023-09-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rentalperson_rentpayment_delete_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalperson',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentalperson',
            name='amount_pending',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
