# Generated by Django 4.1.10 on 2023-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkfarm', '0003_alter_customer_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
