# Generated by Django 4.1.10 on 2023-09-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_ice_block_given', models.PositiveIntegerField()),
                ('one_ice_chip_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ice_chip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_transportation_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icechip.customer')),
            ],
        ),
    ]
