# Generated by Django 4.1.10 on 2023-08-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverallTransportExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_km', models.PositiveIntegerField()),
                ('ending_km', models.PositiveIntegerField()),
                ('money_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_online_payment', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('overall_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.overalltransportexpenses')),
            ],
        ),
    ]
