# Generated by Django 4.1.10 on 2023-09-01 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_expense_transportexpenses_delete_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportexpenses',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
