# Generated by Django 4.1.10 on 2023-09-01 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transportexpenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
